All app+redux
ksenia5516/my-app pull request #4
Opened 2022-05-20 18:25 UTC by ksenia5516

2022-05-24 14:26 UTC, vl-domorad requested changes
В целом все хорошо, исправляй комментарии, на занятии прокомментирую

2022-05-24 14:26 UTC, vl-domorad commented on src/components/Button/Button.tsx
> +const Button: FC<Btn> = ({value, disabled, onClick, className, btnText}) => {
ButtonProps тип называется

2022-05-24 14:26 UTC, vl-domorad commented on src/components/CardPost/CardPost.tsx
> +const CardPost: FC <CardPostType> =  ({id, image, title, text, date}) => {
То же самое

2022-05-24 14:26 UTC, vl-domorad commented on src/components/Input/Input.tsx
>  const Input = (props:any) => {
Типизация

2022-05-24 14:26 UTC, vl-domorad commented on src/pages/Router/Router.tsx
> +            <Route path='*' element={<Navigate to="/" replace/>}/>
Этот роут надо вынести на уровень с '/'

2022-05-24 14:26 UTC, vl-domorad commented on src/common/js.js
> +//     let names = countries.sort((a, b) => (a.country > b.country ? 1 : -1))
Sort мутирует исходный массив, тебе нужно чтобы возвращало новый

2022-05-25 09:18 UTC, ksenia5516 commented on src/components/Button/Button.tsx
> +const Button: FC<Btn> = ({value, disabled, onClick, className, btnText}) => {
ok

2022-05-25 09:19 UTC, ksenia5516 commented on src/components/CardPost/CardPost.tsx
> +const CardPost: FC <CardPostType> =  ({id, image, title, text, date}) => {
ok

2022-06-03 17:10 UTC, ksenia5516 commented on src/components/Input/Input.tsx
>  const Input = (props:any) => {
ok

2022-06-03 17:11 UTC, ksenia5516 commented on src/pages/Router/Router.tsx
> +            <Route path='*' element={<Navigate to="/" replace/>}/>
ok

2022-06-03 17:48 UTC, merged